#ifndef SHARED_CHROME_H
#define SHARED_CHROME_H

#define CHROME_TITLEBAR 46
#define CHROME_BTN 32
#define CHROME_GAP 8
#define CHROME_PAD 12
#define CHROME_RADIUS 16

#define CHROME_CONTROLS_WIDTH \
    (CHROME_PAD + CHROME_BTN + CHROME_GAP + CHROME_BTN + CHROME_GAP + CHROME_BTN)

#endif
